data <- FetchData(x = whole)
cells.after <- length(rownames(data))
print(paste0("cells.before:",cells.before))
print(paste0("cells.after:",cells.after))
print(paste0("cell.diff:", cells.before-cells.after))
